routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Events\MessageCreated;
use App\Http\Controllers\Api\KosController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/message/created', function () {
    MessageCreated::dispatch('loerm ipsum');
});

Route::get('/', [App\Http\Controllers\HomeController::class, 'index']);
Route::get('/browse', [App\Http\Controllers\HomeController::class, 'browse'])->name('browse');
Route::get('/detail/{slug}', [App\Http\Controllers\HomeController::class, 'detail'])->name('kos.detail');
// 
// Route::get('semua-kos-tersedia',[App\Http\Controllers\HomeController::class, 'kosKosan'])->name('semua-kos-tersedia');
Route::resource('object-kos', App\Http\Controllers\ObjectKosController::class);
Route::get('object-kos/{id}/{jarak}', [App\Http\Controllers\ObjectKosController::class, 'show']);
// 
Route::get('/blog/{slug}', [App\Http\Controllers\HomeController::class, 'detailBlog'])->name('blog.detail');
Route::get('lihat-semua-blog', [App\Http\Controllers\HomeController::class, 'lihatSemuaBlog'])->name('lihat-semua-blog');

Route::group(['middleware' => ['auth']], function () {
    Route::get('/home', [App\Http\Controllers\DashboardController::class, 'index'])->name('home');
    Route::resource('user', App\Http\Controllers\UserController::class);
    Route::get('profile', [App\Http\Controllers\UserController::class, 'myProfile'])->name('myProfile');
    Route::post('ganti-password', [App\Http\Controllers\UserController::class, 'gantiPassword'])->name('gantiPassword');
    Route::resource('bank', App\Http\Controllers\BankController::class);
    Route::resource('fasilitas', App\Http\Controllers\FasilitasController::class);
    Route::resource('kos', App\Http\Controllers\KosController::class);
    Route::resource('gallery', App\Http\Controllers\GambarKosController::class);
    Route::resource('kamar', App\Http\Controllers\KamarController::class);
    Route::resource('kos-tersimpan', App\Http\Controllers\KosTersimpanController::class);
    Route::resource('gambar-kamar', App\Http\Controllers\GambarKamarController::class);
    Route::resource('blog', App\Http\Controllers\BlogController::class);
    Route::resource('booking', App\Http\Controllers\BookingController::class);
    Route::post('create-testimonial-rating', [App\Http\Controllers\TestimonialController::class, 'testimonialUpdate'])->name('create-testimonial-rating');
    Route::resource('testimonial', App\Http\Controllers\TestimonialController::class);


    Route::get('success', [App\Http\Controllers\HomeController::class, 'success'])->name('success');
    Route::get('booking/{idKos}/{idKamar}/', [App\Http\Controllers\HomeController::class, 'getBooking']);
    Route::get('terima-booking/{idKamar}/{idBooking}/{idKos}', [App\Http\Controllers\BookingController::class, 'terimaBooking'])->name('terima.booking');
    Route::get('tolak-booking/{idKamar}/{idBooking}/', [App\Http\Controllers\BookingController::class, 'tolakBooking'])->name('tolak.booking');
    Route::get('booking-kos-masuk', [App\Http\Controllers\BookingController::class, 'bookinganKosMasuk'])->name('booking-kos-masuk');
    Route::get('riwayat-kos-saya', [App\Http\Controllers\BookingController::class, 'bookinganSaya'])->name('riwayat-kos-saya');
    Route::get('semua-kos', [App\Http\Controllers\KosController::class, 'tableKos'])->name('semua-kos');
    Route::get('aktifkan-kos/{id}', [App\Http\Controllers\KosController::class, 'aktifkan'])->name('kos.aktifkan');
    Route::get('nonaktifkan-kos/{id}', [App\Http\Controllers\KosController::class, 'nonaktifkan'])->name('kos.nonaktifkan');
    Route::get('kos-tersimpan/{id}/delete', [App\Http\Controllers\KosTersimpanController::class, 'delete'])->name('delete.kos-tersimpan');
    Route::get('delete-gallery/{id}', [App\Http\Controllers\GambarKosController::class, 'deleteGalery'])->name('delete-gallery');
    Route::get('delete-kos/{id}', [App\Http\Controllers\KosController::class, 'deleteKos'])->name('delete-kos');
    Route::get('create-gallery/{id}', [App\Http\Controllers\KosController::class, 'createGallery'])->name('createGallery');
    Route::get('create-gallery-kamar/{id}', [App\Http\Controllers\GambarKamarController::class, 'createGalleryKamar'])->name('gallery.kamar');
    Route::get('delete-gallery-kamar/{id}', [App\Http\Controllers\GambarKamarController::class, 'deleteGalleryKamar'])->name('gallery-kamar.delete');
    Route::get('/ajax/fasilitas-kos/search', [App\Http\Controllers\FasilitasController::class, 'ajaxSearch']);

    Route::get('cetak-pdf/{id}', [App\Http\Controllers\BookingController::class, 'cetakPdf'])->name('cetakPdf');
    Route::get('cetak-semua-booking', [App\Http\Controllers\BookingController::class, 'setakBookingSukses'])->name('cetak-semua-booking');
});


// api untuk tampilkan seluruh data kost
Route::get('/api/data-kost/all', [App\Http\Controllers\Api\KosController::class, 'dataKostAll']);
Route::get('/api/data-kost/detail/{nama_kost}', [App\Http\Controllers\Api\KosController::class, 'dataDetailKost']);
Route::get('/api/data-kost/detail_id/{id_kost}', [App\Http\Controllers\Api\KosController::class, 'dataDetailKostId']);
Route::get('/api/data-kost/getKos/{latitude}/{longitude}', [App\Http\Controllers\Api\KosController::class, 'getKos']);

app/Models/Blog.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Blog extends Model
{
    use HasFactory;

    protected $fillable = [
        'title','gambar','slug','kategori','isi','author'
    ];
}

app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use App\Models\Blog;
use Illuminate\Http\Request;
use Str;
use Storage;
use App\Http\Requests\CreateBlogRequest;

class BlogController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $blogs = Blog::all();
        return view('pages.dashboard.blog.index', compact('blogs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateBlogRequest $request)
    {

        $data = $request->all();
        $data['gambar'] = $request->file('gambar')->store('blog','public');
        $data['slug'] = Str::slug($request->title);
        Blog::create($data);
        return redirect()->back()->with('status','Blog Terlah Ditambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Blog  $blog
     * @return \Illuminate\Http\Response
     */
    public function show(Blog $blog)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Blog  $blog
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $blog = Blog::findOrFail($id);
        return view('pages.dashboard.blog.edit', compact('blog'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Blog  $blog
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'isi' => 'required',
            'title' => 'required',
            'gambar' => 'image|nullable',
            'author' => 'required',
            'kategori' => 'required',
        ]);
        $blog = Blog::findOrFail($id);
        $blog->isi = $request->isi;
        $blog->title = $request->title;
        $blog->kategori = $request->kategori;
        $blog->author = $request->author;
        $blog->slug = Str::slug($request->title);
        if($request->hasFile('gambar')){
            if($request->gambar && file_exists(storage_path('app/public/'.$request->gambar))){
                Storage::delete('public/'.$request->gambar);
            }
            $file = $request->file('gambar')->store('gambars','public');
            $blog->gambar = $file;
        } 
        $blog->save();
        return redirect()->back()->with('status','Blog  Berhasil Diubah');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Blog  $blog
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = Blog::findOrFail($id);
        $data->delete();
        return redirect()->back()->with('status','Blog Berhasil Dihapus');
    }
}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Kos;

class DashboardController extends Controller
{
    public function index()
    {
        $jmlKos = Kos::where('status','=','aktifkan')->count();
        return view('pages.dashboard.index', compact('jmlKos'));
    }
}

resources/views/pages/dashboard/blog/edit.blade.php
@extends('layouts.dashboard')

@section('title')
    Edit Blog
@stop

@section('content')
<section class="section">
          <div class="section-header">
            <div class="section-header-breadcrumb">
              <div class="breadcrumb active"><a href="{{route('home')}}">Dashboard</a></div>
              <div class="breadcrumb">{{$blog->title}}</div>
            </div>
          </div>
          <div class="section-body">
            <div class="row ">
            
            @if(session('status'))
                <div class="alert alert-warning col-10" role="alert">
                    {{session('status')}}
                </div>
            @endif
              <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <div class="card-title">Edit Bank - {{$blog->title}}</div>
                    </div>
                    <div class="card-body">
                        <form action="{{route('blog.update',$blog->id)}}" method="post" enctype="multipart/form-data">
                            @csrf @method('put')
                        <div class="form-group">
                            <label for="title">Title</label>
                            <input type="text" class="form-control @error('title') is-invalid @enderror" id="title" name="title" value="{{old('title') ? old('title') : $blog->title}}">
                            @error('title')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="author">Author</label>
                            <input type="text" class="form-control @error('author') is-invalid @enderror" id="author" name="author" value="{{old('author') ? old('author') : $blog->author}}">
                            @error('author')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="kategori">Kategori</label>
                            <input type="text" class="form-control @error('kategori') is-invalid @enderror" id="kategori" name="kategori" value="{{old('kategori') ? old('kategori') : $blog->kategori}}">
                            @error('kategori')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="gambar">gambar</label>
                            <input type="file" name="gambar" class="form-control @error('gambar') is-invalid @enderror"> <br>
                            @error('gambar')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                            <i>Kosongkan Inputan Jika tidak ingin rubah gambar.</i>
                            <br>
                            <img src="{{Storage::url($blog->gambar)}}" alt="" style="width: 200px;"> <br>
                        </div>
                        <div class="form-group">
                            <label for="Isi">Isi</label>
                            <textarea required name="isi" id="editor">{!!$blog->isi!!}</textarea>
                            @error('Isi')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                        <button class="btn btn-sm btn-block text-center btn-success" type="submit">Ubah</button>
                        <a href="{{route('blog.index')}}" class="btn btn-sm btn-block text-center btn-secondary" type="submit">Kembali</a>
                        </form>
                    </div>
                </div>
              </div>
            </div>
          </div>
        </section>
@stop

resources/views/pages/dashboard/blog/index.blade.php
@extends('layouts.dashboard')

@section('title')
    Kelola Blogger
@stop

@section('content')
<section class="section">
          <div class="section-header">
            <div class="section-header-breadcrumb">
              <div class="breadcrumb active"><a href="{{route('home')}}">Dashboard</a></div>
              <div class="breadcrumb">kelola Blogger</div>
            </div>
          </div>
          <div class="section-body">
            <div class="section-header-button mb-3">
              <button href="#" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Add New</button>
            </div>
            <div class="row ">
            
            @if(session('status'))
                <div class="alert alert-warning col-12" role="alert">
                    {{session('status')}}
                </div>
            @endif
              <div class="col-12">
                <div class="card">
                  <div class="card-body">

                    <div class="clearfix mb-3"></div>

                    <div class="table-responsive">
                      <table class="table table-striped" id="table_id">
                        <thead>
                            <tr>
                                <th>Author</th>
                                <th>Title</th>
                                <th>Gambar</th>
                                <th>Slug</th>
                                <th>Kategori</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($blogs as $blog)
                            <tr>
                                <td>{{$blog->author}}
                                    <form action="{{route('blog.destroy',$blog->id)}}" method="post">
                                        @csrf @method('delete')
                                        <div class="table-links">
                                        <div class="bullet"></div>
                                        <a href="{{route('blog.edit',$blog->id)}}">Edit</a>
                                        <div class="bullet"></div>
                                        <button onClick="return confirm('Are You Sure ?')" type="submit" class="text-danger btn btn-sm">Trash</button>
                                        </div>
                                    </form>                                   
                                </td>
                                <td>
                                    {{$blog->title}}
                                </td>
                                <td>
                                    <img src="{{Storage::url($blog->gambar)}}" alt="" style="width:100px;">
                                </td>
                                <td>
                                <a  href="{{route('blog.detail',$blog->slug)}}">{{$blog->title}}</a>
                                </td>
                                <td>
                                    {{$blog->kategori}}
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog dialog-md" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Tambah Blog</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form action="{{route('blog.store')}}" method="post" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label for="title">Title</label>
                <input type="text" class="form-control @error('title') is-invalid @enderror" id="title" name="title">
                @error('title')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror
            </div>
            <div class="form-group">
                <label for="author">Penulis</label>
                <input type="text" class="form-control @error('author') is-invalid @enderror" id="author" name="author">
                @error('author')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror
            </div>
            <div class="form-group">
                <label for="gambar">Gambar</label>
                <input type="file" class="form-control @error('gambar') is-invalid @enderror" id="gambar" name="gambar">
                @error('gambar')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror
            </div>
            <div class="form-group">
                <label for="kategori">kategori</label>
                <input type="text" class="form-control @error('kategori') is-invalid @enderror" id="kategori" name="kategori">
                @error('kategori')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror
            </div>
            <div class="form-group">
                <label for="Isi">Isi</label>
                <textarea name="isi" id="editor"></textarea>
                @error('isi')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror
            </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
      </form>
    </div>
  </div>
</div>
@stop

@push('scripts')
<script>
    $(document).ready( function () {
        $('#table_id').DataTable();
    } );
</script>
@endpush