routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Events\MessageCreated;
use App\Http\Controllers\Api\KosController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/message/created', function () {
    MessageCreated::dispatch('loerm ipsum');
});

Route::get('/', [App\Http\Controllers\HomeController::class, 'index']);
Route::get('/browse', [App\Http\Controllers\HomeController::class, 'browse'])->name('browse');
Route::get('/detail/{slug}', [App\Http\Controllers\HomeController::class, 'detail'])->name('kos.detail');
// 
// Route::get('semua-kos-tersedia',[App\Http\Controllers\HomeController::class, 'kosKosan'])->name('semua-kos-tersedia');
Route::resource('object-kos', App\Http\Controllers\ObjectKosController::class);
Route::get('object-kos/{id}/{jarak}', [App\Http\Controllers\ObjectKosController::class, 'show']);
// 
Route::get('/blog/{slug}', [App\Http\Controllers\HomeController::class, 'detailBlog'])->name('blog.detail');
Route::get('lihat-semua-blog', [App\Http\Controllers\HomeController::class, 'lihatSemuaBlog'])->name('lihat-semua-blog');

Route::group(['middleware' => ['auth']], function () {
    Route::get('/home', [App\Http\Controllers\DashboardController::class, 'index'])->name('home');
    Route::resource('user', App\Http\Controllers\UserController::class);
    Route::get('profile', [App\Http\Controllers\UserController::class, 'myProfile'])->name('myProfile');
    Route::post('ganti-password', [App\Http\Controllers\UserController::class, 'gantiPassword'])->name('gantiPassword');
    Route::resource('bank', App\Http\Controllers\BankController::class);
    Route::resource('fasilitas', App\Http\Controllers\FasilitasController::class);
    Route::resource('kos', App\Http\Controllers\KosController::class);
    Route::resource('gallery', App\Http\Controllers\GambarKosController::class);
    Route::resource('kamar', App\Http\Controllers\KamarController::class);
    Route::resource('kos-tersimpan', App\Http\Controllers\KosTersimpanController::class);
    Route::resource('gambar-kamar', App\Http\Controllers\GambarKamarController::class);
    Route::resource('blog', App\Http\Controllers\BlogController::class);
    Route::resource('booking', App\Http\Controllers\BookingController::class);
    Route::post('create-testimonial-rating', [App\Http\Controllers\TestimonialController::class, 'testimonialUpdate'])->name('create-testimonial-rating');
    Route::resource('testimonial', App\Http\Controllers\TestimonialController::class);


    Route::get('success', [App\Http\Controllers\HomeController::class, 'success'])->name('success');
    Route::get('booking/{idKos}/{idKamar}/', [App\Http\Controllers\HomeController::class, 'getBooking']);
    Route::get('terima-booking/{idKamar}/{idBooking}/{idKos}', [App\Http\Controllers\BookingController::class, 'terimaBooking'])->name('terima.booking');
    Route::get('tolak-booking/{idKamar}/{idBooking}/', [App\Http\Controllers\BookingController::class, 'tolakBooking'])->name('tolak.booking');
    Route::get('booking-kos-masuk', [App\Http\Controllers\BookingController::class, 'bookinganKosMasuk'])->name('booking-kos-masuk');
    Route::get('riwayat-kos-saya', [App\Http\Controllers\BookingController::class, 'bookinganSaya'])->name('riwayat-kos-saya');
    Route::get('semua-kos', [App\Http\Controllers\KosController::class, 'tableKos'])->name('semua-kos');
    Route::get('aktifkan-kos/{id}', [App\Http\Controllers\KosController::class, 'aktifkan'])->name('kos.aktifkan');
    Route::get('nonaktifkan-kos/{id}', [App\Http\Controllers\KosController::class, 'nonaktifkan'])->name('kos.nonaktifkan');
    Route::get('kos-tersimpan/{id}/delete', [App\Http\Controllers\KosTersimpanController::class, 'delete'])->name('delete.kos-tersimpan');
    Route::get('delete-gallery/{id}', [App\Http\Controllers\GambarKosController::class, 'deleteGalery'])->name('delete-gallery');
    Route::get('delete-kos/{id}', [App\Http\Controllers\KosController::class, 'deleteKos'])->name('delete-kos');
    Route::get('create-gallery/{id}', [App\Http\Controllers\KosController::class, 'createGallery'])->name('createGallery');
    Route::get('create-gallery-kamar/{id}', [App\Http\Controllers\GambarKamarController::class, 'createGalleryKamar'])->name('gallery.kamar');
    Route::get('delete-gallery-kamar/{id}', [App\Http\Controllers\GambarKamarController::class, 'deleteGalleryKamar'])->name('gallery-kamar.delete');
    Route::get('/ajax/fasilitas-kos/search', [App\Http\Controllers\FasilitasController::class, 'ajaxSearch']);

    Route::get('cetak-pdf/{id}', [App\Http\Controllers\BookingController::class, 'cetakPdf'])->name('cetakPdf');
    Route::get('cetak-semua-booking', [App\Http\Controllers\BookingController::class, 'setakBookingSukses'])->name('cetak-semua-booking');
});


// api untuk tampilkan seluruh data kost
Route::get('/api/data-kost/all', [App\Http\Controllers\Api\KosController::class, 'dataKostAll']);
Route::get('/api/data-kost/detail/{nama_kost}', [App\Http\Controllers\Api\KosController::class, 'dataDetailKost']);
Route::get('/api/data-kost/detail_id/{id_kost}', [App\Http\Controllers\Api\KosController::class, 'dataDetailKostId']);
Route::get('/api/data-kost/getKos/{latitude}/{longitude}', [App\Http\Controllers\Api\KosController::class, 'getKos']);

resources/views/includes/backend/footer.blade.php
<footer class="main-footer">
    <div class="footer-left">
        &copy;
        Usakti<span class="text-success"> Kos</span> - <?php echo date('Y'); ?> <i class="fa fa-home"></i>
    </div>
</footer>

resources/views/includes/backend/navbar.blade.php
<div class="navbar-bg"></div>
    <nav class="navbar navbar-expand-lg main-navbar">
        <form class="form-inline mr-auto">
          <ul class="navbar-nav mr-3">
            <li><a href="#" data-toggle="sidebar" class="nav-link nav-link-lg"><i class="fas fa-bars"></i></a></li>
          </ul>
        </form>
        @if(Auth::user()->roles == 'pemilik')
        <!-- pemilik -->
        <ul class="navbar-nav navbar-right">
          @php 
          $bookingMasuk = App\Models\Booking_detail::with(['booking.user','kos'])
                ->whereHas('kos', function($kos){$kos->where('user_id', \Auth::user()->id);})
                ->whereHas('booking', function($booking){$booking->where('status', '=','menunggu');})
                ->get();
          @endphp
            @if($bookingMasuk->count() > 0)
              <li class="dropdown dropdown-list-toggle"><a href="#" data-toggle="dropdown" class="nav-link notification-toggle nav-link-lg beep "><i class="far fa-bell"></i></a>
            @else
              <li class="dropdown dropdown-list-toggle"><a href="#" data-toggle="dropdown" class="nav-link notification-toggle nav-link-lg "><i class="far fa-bell"></i></a>
            @endif
            <div class="dropdown-menu dropdown-list dropdown-menu-right">
              <div class="dropdown-header">Notifications {{$bookingMasuk->count()}}
              </div>
              <div class="dropdown-list-content dropdown-list-icons">
              @foreach($bookingMasuk as $booking)
                <a href="#" class="dropdown-item dropdown-item-unread">
                  <div class="dropdown-item-icon bg-primary text-white">
                    <i class="fas fa-code"></i>
                  </div>
                  <div class="dropdown-item-desc">
                    Kos "{{$booking->kos->nama_kos}}" telah diBooking <br>
                    Oleh - {{$booking->booking->user->name}}
                    <div class="time text-primary">{{\Carbon\Carbon::createFromTimeStamp(strtotime($booking->booking->created_at))->diffForHumans()}}</div>
                  </div>
                </a>
              @endforeach
              </div>
              <div class="dropdown-footer text-center">
                <a href="{{route('booking-kos-masuk')}}">Lihat Semua <i class="fas fa-chevron-right"></i></a>
              </div>
            </div>
          </li>
          <li class="dropdown"><a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
          @if (Auth::user()->avatar)
              <img src="{{ Storage::url(Auth::user()->avatar) }}" class="rounded-circle mr-1">
          @else
              <img src="https://ui-avatars.com/api/?name={{ Auth::user()->name }}" height="40" class="rounded-circle mr-1" />
          @endif
            <div class="d-sm-none d-lg-inline-block">Hi, {{Auth::user()->name}}</div></a>
            <div class="dropdown-menu dropdown-menu-right">
            <a href="{{route('myProfile')}}" class="dropdown-item has-icon">
                <i class="fas fa-cog"></i> Setting Profile
              </a>
              <a href="{{url('/logout')}}" class="dropdown-item has-icon text-danger" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                <i class="fas fa-sign-out-alt"></i> Logout
              </a>
              <form id="logout-form" action="{{url('/logout')}}" method="POST" style="display: none;">
                @csrf
              </form>
            </div>
          </li>
        </ul>
        @elseif(Auth::user()->roles == 'admin')
        <!-- admin -->
        <ul class="navbar-nav navbar-right">
          @php 
            $kosBaruDaftar = App\Models\Kos::with('user')->where('status','=','nonaktif')->get();
          @endphp
            @if($kosBaruDaftar->count() > 0)
              <li class="dropdown dropdown-list-toggle"><a href="#" data-toggle="dropdown" class="nav-link notification-toggle nav-link-lg beep "><i class="far fa-bell"></i></a>
            @else
              <li class="dropdown dropdown-list-toggle"><a href="#" data-toggle="dropdown" class="nav-link notification-toggle nav-link-lg "><i class="far fa-bell"></i></a>
            @endif
            <div class="dropdown-menu dropdown-list dropdown-menu-right">
              <div class="dropdown-header">Notifications {{$kosBaruDaftar->count()}}
              </div>
              <div class="dropdown-list-content dropdown-list-icons">
              @foreach($kosBaruDaftar as $kos)
                <a href="#" class="dropdown-item dropdown-item-unread">
                  <div class="dropdown-item-icon bg-primary text-white">
                    <i class="fas fa-code"></i>
                  </div>
                  <div class="dropdown-item-desc">
                    {{$kos->user->name}} telah mendaftarkan kos "{{$kos->nama_kos}}"
                    <div class="time text-primary">{{\Carbon\Carbon::createFromTimeStamp(strtotime($kos->created_at))->diffForHumans()}}</div>
                  </div>
                </a>
              @endforeach
              </div>
              <div class="dropdown-footer text-center">
                <a href="{{route('semua-kos')}}">Lihat Semua <i class="fas fa-chevron-right"></i></a>
              </div>
            </div>
          </li>
          <li class="dropdown"><a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
          @if (Auth::user()->avatar)
              <img src="{{ Storage::url(Auth::user()->avatar) }}" class="rounded-circle mr-1">
          @else
              <img src="https://ui-avatars.com/api/?name={{ Auth::user()->name }}" height="40" class="rounded-circle mr-1" />
          @endif
            <div class="d-sm-none d-lg-inline-block">Hi, {{Auth::user()->name}}</div></a>
            <div class="dropdown-menu dropdown-menu-right">
            <a href="{{route('myProfile')}}" class="dropdown-item has-icon">
                <i class="fas fa-cog"></i> Setting Profile
              </a>
              <a href="{{url('/logout')}}" class="dropdown-item has-icon text-danger" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                <i class="fas fa-sign-out-alt"></i> Logout
              </a>
              <form id="logout-form" action="{{url('/logout')}}" method="POST" style="display: none;">
                @csrf
              </form>
            </div>
          </li>
        </ul>
        @else
        <!-- member -->
        <ul class="navbar-nav navbar-right">
          <li class="dropdown"><a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
          @if (Auth::user()->avatar)
              <img src="{{ Storage::url(Auth::user()->avatar) }}" class="rounded-circle mr-1">
          @else
              <img src="https://ui-avatars.com/api/?name={{ Auth::user()->name }}" height="40" class="rounded-circle mr-1" />
          @endif
            <div class="d-sm-none d-lg-inline-block">Hi, {{Auth::user()->name}}</div></a>
            <div class="dropdown-menu dropdown-menu-right">
            <a href="{{route('myProfile')}}" class="dropdown-item has-icon">
                <i class="fas fa-cog"></i> Setting Profile
              </a>
              <a href="{{url('/logout')}}" class="dropdown-item has-icon text-danger" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                <i class="fas fa-sign-out-alt"></i> Logout
              </a>
              <form id="logout-form" action="{{url('/logout')}}" method="POST" style="display: none;">
                @csrf
              </form>
            </div>
          </li>
        </ul>
        @endif
      </nav>

resources/views/includes/backend/scripts.blade.php
  <!-- General JS Scripts -->
  <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.nicescroll/3.7.6/jquery.nicescroll.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
  <script src="/backend/assets/js/stisla.js"></script>
  <!-- JS Libraies -->

  <script src="https://js.api.here.com/v3/3.1/mapsjs-core.js" type="text/javascript" charset="utf-8"></script>
    <!-- <script src="{{ asset('js/mapsjs-core.js') }}"></script> -->
    <script src="https://js.api.here.com/v3/3.1/mapsjs-service.js" type="text/javascript" charset="utf-8"></script>
    <!-- <script src="{{ asset('js/mapsjs-service.js') }}"></script> -->
    <script src="https://js.api.here.com/v3/3.1/mapsjs-ui.js" type="text/javascript" charset="utf-8"></script>
    <!-- <script src="{{ asset('js/mapsjs-ui.js') }}"></script> -->
    <link rel="stylesheet" type="text/css" href="https://js.api.here.com/v3/3.1/mapsjs-ui.css" />
    <!-- <script src="{{ asset('css/mapsjs-ui.css') }}"></script> -->
    <script src="https://js.api.here.com/v3/3.1/mapsjs-mapevents.js" type="text/javascript" charset="utf-8"></script>
    <!-- <script src="{{ asset('js/mapsjs-mapevents.js') }}"></script> -->

  <!-- Template JS File -->
  <script src="/backend/assets/js/scripts.js"></script>
  <script src="/backend/assets/js/here.js"></script>
  <script src="/backend/assets/js/custom.js"></script>
  <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.js"></script>
  <script src="https://cdn.ckeditor.com/ckeditor5/29.0.0/classic/ckeditor.js"></script>
   <script>
        window.hereApiKey = "{{ env('HERE_API_KEY') }}"
    </script>
  <script>
    ClassicEditor
            .create( document.querySelector( '#editor' ) )
            .then( editor => {
                    console.log( editor );
            } )
            .catch( error => {
                    console.error( error );
            } );
  </script>

resources/views/includes/backend/sidebar.blade.php
<div class="main-sidebar bg-style">
    <aside id="sidebar-wrapper">
        <div class="sidebar-brand">
            <a href="{{ env('APP_URL') }}">Kosan<span class="text-success"> Usakti</span></a>
        </div>
        <div class="sidebar-brand sidebar-brand-sm">
            <a href="{{ env('APP_URL') }}">K.U</a>
        </div>
        <ul class="sidebar-menu">
            <li class="menu-header">Dashboard</li>
            <li><a class="nav-link" href="{{route('home')}}"><i class="fas fa-fire"></i> <span>Dashboard</span></a></li>
            <li class="menu-header">Menu</li>
            @if(Auth::user()->roles == 'admin')
            <li><a class="nav-link" href="{{route('user.index')}}"><i class="fa fa-users"></i> <span>Kelola
                        Pengguna</span></a></li>
            <li><a class="nav-link" href="{{route('semua-kos')}}"><i class="fa fa-home"></i> <span>Semua Kos</span></a>
            </li>
            <li><a class="nav-link" href="{{route('fasilitas.index')}}"><i class="fa fa-list"></i> <span>Kelola
                        Fasilitas</span></a></li>
            <li><a class="nav-link" href="{{route('blog.index')}}"><i class="fa fa-list"></i> <span>Kelola
                        Blog</span></a></li>
            @elseif(Auth::user()->roles == 'pemilik')
            <li><a class="nav-link" href="{{route('kos.index')}}"><i class="fa fa-home"></i> <span>Kelola Kos</span></a>
            </li>
            <li><a class="nav-link" href="{{route('fasilitas.index')}}"><i class="fa fa-list"></i> <span>Kelola
                        Fasilitas</span></a></li>
            <!-- <li><a class="nav-link" href="{{route('booking-kos-masuk')}}"><i class="fa fa-list"></i> <span>Booking Kos
                        Masuk</span></a></li> 
            <li><a class="nav-link" href="{{route('bank.index')}}"><i class="fa fa-credit-card"></i> <span>Kelola
                        Rekening</span></a></li>-->
            @else
            <!-- <li><a class="nav-link" href="{{route('riwayat-kos-saya')}}"><i class="fa fa-list"></i> <span>Riwayat Kos
                        Saya</span></a></li>
            <li><a class="nav-link" href="{{route('testimonial.index')}}"><i class="fa fa-comment"></i> <span>Beri
                        Testimonial</span></a></li>-->
            <li><a class="nav-link" href="{{route('kos-tersimpan.index')}}"><i class="fa fa-heart"></i> <span>Kos
                        Favorit</span></a></li> 
            @endif
        </ul>
    </aside>
</div>

resources/views/includes/backend/styles.blade.php
  <!-- General CSS Files -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

  <!-- CSS Libraries -->

  <!-- Template CSS -->
  <link rel="stylesheet" href="{{ asset('backend/assets/css/style.css') }}">
  <link rel="stylesheet" href="{{ asset('backend/assets/css/components.css') }}">
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.25/css/jquery.dataTables.css">