routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Events\MessageCreated;
use App\Http\Controllers\Api\KosController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/message/created', function () {
    MessageCreated::dispatch('loerm ipsum');
});

Route::get('/', [App\Http\Controllers\HomeController::class, 'index']);
Route::get('/browse', [App\Http\Controllers\HomeController::class, 'browse'])->name('browse');
Route::get('/detail/{slug}', [App\Http\Controllers\HomeController::class, 'detail'])->name('kos.detail');
// 
// Route::get('semua-kos-tersedia',[App\Http\Controllers\HomeController::class, 'kosKosan'])->name('semua-kos-tersedia');
Route::resource('object-kos', App\Http\Controllers\ObjectKosController::class);
Route::get('object-kos/{id}/{jarak}', [App\Http\Controllers\ObjectKosController::class, 'show']);
// 
Route::get('/blog/{slug}', [App\Http\Controllers\HomeController::class, 'detailBlog'])->name('blog.detail');
Route::get('lihat-semua-blog', [App\Http\Controllers\HomeController::class, 'lihatSemuaBlog'])->name('lihat-semua-blog');

Route::group(['middleware' => ['auth']], function () {
    Route::get('/home', [App\Http\Controllers\DashboardController::class, 'index'])->name('home');
    Route::resource('user', App\Http\Controllers\UserController::class);
    Route::get('profile', [App\Http\Controllers\UserController::class, 'myProfile'])->name('myProfile');
    Route::post('ganti-password', [App\Http\Controllers\UserController::class, 'gantiPassword'])->name('gantiPassword');
    Route::resource('bank', App\Http\Controllers\BankController::class);
    Route::resource('fasilitas', App\Http\Controllers\FasilitasController::class);
    Route::resource('kos', App\Http\Controllers\KosController::class);
    Route::resource('gallery', App\Http\Controllers\GambarKosController::class);
    Route::resource('kamar', App\Http\Controllers\KamarController::class);
    Route::resource('kos-tersimpan', App\Http\Controllers\KosTersimpanController::class);
    Route::resource('gambar-kamar', App\Http\Controllers\GambarKamarController::class);
    Route::resource('blog', App\Http\Controllers\BlogController::class);
    Route::resource('booking', App\Http\Controllers\BookingController::class);
    Route::post('create-testimonial-rating', [App\Http\Controllers\TestimonialController::class, 'testimonialUpdate'])->name('create-testimonial-rating');
    Route::resource('testimonial', App\Http\Controllers\TestimonialController::class);


    Route::get('success', [App\Http\Controllers\HomeController::class, 'success'])->name('success');
    Route::get('booking/{idKos}/{idKamar}/', [App\Http\Controllers\HomeController::class, 'getBooking']);
    Route::get('terima-booking/{idKamar}/{idBooking}/{idKos}', [App\Http\Controllers\BookingController::class, 'terimaBooking'])->name('terima.booking');
    Route::get('tolak-booking/{idKamar}/{idBooking}/', [App\Http\Controllers\BookingController::class, 'tolakBooking'])->name('tolak.booking');
    Route::get('booking-kos-masuk', [App\Http\Controllers\BookingController::class, 'bookinganKosMasuk'])->name('booking-kos-masuk');
    Route::get('riwayat-kos-saya', [App\Http\Controllers\BookingController::class, 'bookinganSaya'])->name('riwayat-kos-saya');
    Route::get('semua-kos', [App\Http\Controllers\KosController::class, 'tableKos'])->name('semua-kos');
    Route::get('aktifkan-kos/{id}', [App\Http\Controllers\KosController::class, 'aktifkan'])->name('kos.aktifkan');
    Route::get('nonaktifkan-kos/{id}', [App\Http\Controllers\KosController::class, 'nonaktifkan'])->name('kos.nonaktifkan');
    Route::get('kos-tersimpan/{id}/delete', [App\Http\Controllers\KosTersimpanController::class, 'delete'])->name('delete.kos-tersimpan');
    Route::get('delete-gallery/{id}', [App\Http\Controllers\GambarKosController::class, 'deleteGalery'])->name('delete-gallery');
    Route::get('delete-kos/{id}', [App\Http\Controllers\KosController::class, 'deleteKos'])->name('delete-kos');
    Route::get('create-gallery/{id}', [App\Http\Controllers\KosController::class, 'createGallery'])->name('createGallery');
    Route::get('create-gallery-kamar/{id}', [App\Http\Controllers\GambarKamarController::class, 'createGalleryKamar'])->name('gallery.kamar');
    Route::get('delete-gallery-kamar/{id}', [App\Http\Controllers\GambarKamarController::class, 'deleteGalleryKamar'])->name('gallery-kamar.delete');
    Route::get('/ajax/fasilitas-kos/search', [App\Http\Controllers\FasilitasController::class, 'ajaxSearch']);

    Route::get('cetak-pdf/{id}', [App\Http\Controllers\BookingController::class, 'cetakPdf'])->name('cetakPdf');
    Route::get('cetak-semua-booking', [App\Http\Controllers\BookingController::class, 'setakBookingSukses'])->name('cetak-semua-booking');
});


// api untuk tampilkan seluruh data kost
Route::get('/api/data-kost/all', [App\Http\Controllers\Api\KosController::class, 'dataKostAll']);
Route::get('/api/data-kost/detail/{nama_kost}', [App\Http\Controllers\Api\KosController::class, 'dataDetailKost']);
Route::get('/api/data-kost/detail_id/{id_kost}', [App\Http\Controllers\Api\KosController::class, 'dataDetailKostId']);
Route::get('/api/data-kost/getKos/{latitude}/{longitude}', [App\Http\Controllers\Api\KosController::class, 'getKos']);

app/Models/Bank.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Bank extends Model
{
    use HasFactory;

    protected $fillable = [
        'no_rek','nama_nasabah','nama_bank','user_id'
    ];

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id');
    }
}

app/Http/Controllers/BankController.php
<?php

namespace App\Http\Controllers;

use App\Models\Bank;
use Illuminate\Http\Request;

class BankController extends Controller
{
    /**
     * Display a listing of the resource. 123
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $banks = Bank::where('user_id', \Auth::user()->id)->get();
        return view('pages.dashboard.bank.index', compact('banks'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $data = $request->all(); 
        $data['status'] = 'aktif';
        $data['user_id'] = \Auth::user()->id;
        Bank::create($data);
        return redirect()->back()->with('status','Nomor Rekening Berhasil Ditambahkan.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Bank  $bank
     * @return \Illuminate\Http\Response
     */
    public function show(Bank $bank)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Bank  $bank
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $bank = Bank::findOrFail($id); 
        return view('pages.dashboard.bank.edit', compact('bank'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Bank  $bank
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->all();
        $item = Bank::findOrFail($id);
        $item->update($data);

        return redirect()->back()->with('status',' Bank Berhasil Diupdate');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Bank  $bank
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = Bank::findOrFail($id);
        $data->delete();
        return redirect()->back()->with('status','Bank Berhasil Dihapus');
    }
}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Kos;

class DashboardController extends Controller
{
    public function index()
    {
        $jmlKos = Kos::where('status','=','aktifkan')->count();
        return view('pages.dashboard.index', compact('jmlKos'));
    }
}

resources/views/pages/dashboard/bank/edit.blade.php
@extends('layouts.dashboard')

@section('title')
    Edit Bank
@stop

@section('content')
<section class="section">
          <div class="section-header">
            <div class="section-header-breadcrumb">
              <div class="breadcrumb active"><a href="{{route('home')}}">Dashboard</a></div>
              <div class="breadcrumb">{{$bank->nama_bank}}</div>
            </div>
          </div>
          <div class="section-body">
            <div class="row ">
            
            @if(session('status'))
                <div class="alert alert-warning col-10" role="alert">
                    {{session('status')}}
                </div>
            @endif
              <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <div class="card-title">Edit Bank - {{$bank->nama_bank}}</div>
                    </div>
                    <div class="card-body">
                        <form action="{{route('bank.update',$bank->id)}}" method="post">
                            @csrf @method('put')
                        <div class="form-group">
                            <label for="nama_nasabah">Nama Pemilik</label>
                            <input type="text" class="form-control @error('nama_nasabah') is-invalid @enderror" id="nama_nasabah" name="nama_nasabah" value="{{old('nama_nasabah') ? od('nama_nasabah') : $bank->nama_nasabah}}">
                            @error('nama_nasabah')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="nama_bank">Nama Bank</label>
                            <input type="text" class="form-control @error('nama_bank') is-invalid @enderror" id="nama_bank" name="nama_bank" value="{{old('nama_bank') ? od('nama_bank') : $bank->nama_bank}}">
                            @error('nama_bank')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="no_rek">Nomor Rekening</label>
                            <input type="text" class="form-control @error('no_rek') is-invalid @enderror" id="no_rek" name="no_rek" value="{{old('no_rek') ? od('no_rek') : $bank->no_rek}}">
                            @error('no_rek')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                            <button class="btn btn-sm btn-block text-center btn-success" type="submit">Ubah</button>
                            <a href="{{route('bank.index')}}" class="mt-2 btn btn-sm btn-block text-center btn-secondary" type="submit">Kembali</a>
                        </form>
                    </div>
                </div>
              </div>
            </div>
          </div>
        </section>
@stop

resources/views/pages/dashboard/bank/index.blade.php
@extends('layouts.dashboard')

@section('title')
    Kelola Fasilitas
@stop

@section('content')
<section class="section">
          <div class="section-header">
            <div class="section-header-breadcrumb">
              <div class="breadcrumb active"><a href="{{route('home')}}">Dashboard</a></div>
              <div class="breadcrumb">Semua Bank</div>
            </div>
          </div>
          <div class="section-body">
            <div class="section-header-button mb-3">
              <button href="#" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Tambah Rekening</button>
            </div>
            <div class="row ">
            
            @if(session('status'))
                <div class="alert alert-warning col-12" role="alert">
                    {{session('status')}}
                </div>
            @endif
              <div class="col-12">
                <div class="card">
                  <div class="card-body">

                    <div class="clearfix mb-3"></div>

                    <div class="table-responsive">
                      <table class="table table-striped" id="table_id">
                        <thead>
                            <tr>
                                <th>Nama Pemilik</th>
                                <th>Nomor Rekening</th>
                                <th>Nama Bank</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($banks as $bank)
                            <tr>
                                <td>{{$bank->nama_nasabah}}
                                    <form action="{{route('bank.destroy',$bank->id)}}" method="post">
                                        @csrf @method('delete')
                                        <div class="table-links">
                                        <div class="bullet"></div>
                                        <a href="{{route('bank.edit',$bank->id)}}">Edit</a>
                                        <div class="bullet"></div>
                                        <button onClick="return confirm('Are You Sure ?')" type="submit" class="text-danger btn btn-sm">Trash</button>
                                        </div>
                                    </form>                                   
                                </td>
                                <td>
                                    {{$bank->no_rek}}
                                </td>
                                <td>
                                    {{$bank->nama_bank}}
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Tambah Rekening</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form action="{{route('bank.store')}}" method="post">
            @csrf
            <div class="form-group">
                <label for="nama_nasabah">Nama Pemilik</label>
                <input type="text" class="form-control" id="nama_nasabah" name="nama_nasabah">
            </div>
            <div class="form-group">
                <label for="nama_bank">Nama Bank</label>
                <input type="text" name="nama_bank" class="form-control" id="nama_bank">
            </div>
            <div class="form-group">
                <label for="no_rek">Nomor Rekekning</label>
                <input type="number" name="no_rek" class="form-control" id="no_rek">
            </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
      </form>
    </div>
  </div>
</div>
@stop

@push('scripts')
<script>
    $(document).ready( function () {
        $('#table_id').DataTable();
    } );
</script>
@endpush