routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Events\MessageCreated;
use App\Http\Controllers\Api\KosController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/message/created', function () {
    MessageCreated::dispatch('loerm ipsum');
});

Route::get('/', [App\Http\Controllers\HomeController::class, 'index']);
Route::get('/browse', [App\Http\Controllers\HomeController::class, 'browse'])->name('browse');
Route::get('/detail/{slug}', [App\Http\Controllers\HomeController::class, 'detail'])->name('kos.detail');
// 
// Route::get('semua-kos-tersedia',[App\Http\Controllers\HomeController::class, 'kosKosan'])->name('semua-kos-tersedia');
Route::resource('object-kos', App\Http\Controllers\ObjectKosController::class);
Route::get('object-kos/{id}/{jarak}', [App\Http\Controllers\ObjectKosController::class, 'show']);
// 
Route::get('/blog/{slug}', [App\Http\Controllers\HomeController::class, 'detailBlog'])->name('blog.detail');
Route::get('lihat-semua-blog', [App\Http\Controllers\HomeController::class, 'lihatSemuaBlog'])->name('lihat-semua-blog');

Route::group(['middleware' => ['auth']], function () {
    Route::get('/home', [App\Http\Controllers\DashboardController::class, 'index'])->name('home');
    Route::resource('user', App\Http\Controllers\UserController::class);
    Route::get('profile', [App\Http\Controllers\UserController::class, 'myProfile'])->name('myProfile');
    Route::post('ganti-password', [App\Http\Controllers\UserController::class, 'gantiPassword'])->name('gantiPassword');
    Route::resource('bank', App\Http\Controllers\BankController::class);
    Route::resource('fasilitas', App\Http\Controllers\FasilitasController::class);
    Route::resource('kos', App\Http\Controllers\KosController::class);
    Route::resource('gallery', App\Http\Controllers\GambarKosController::class);
    Route::resource('kamar', App\Http\Controllers\KamarController::class);
    Route::resource('kos-tersimpan', App\Http\Controllers\KosTersimpanController::class);
    Route::resource('gambar-kamar', App\Http\Controllers\GambarKamarController::class);
    Route::resource('blog', App\Http\Controllers\BlogController::class);
    Route::resource('booking', App\Http\Controllers\BookingController::class);
    Route::post('create-testimonial-rating', [App\Http\Controllers\TestimonialController::class, 'testimonialUpdate'])->name('create-testimonial-rating');
    Route::resource('testimonial', App\Http\Controllers\TestimonialController::class);


    Route::get('success', [App\Http\Controllers\HomeController::class, 'success'])->name('success');
    Route::get('booking/{idKos}/{idKamar}/', [App\Http\Controllers\HomeController::class, 'getBooking']);
    Route::get('terima-booking/{idKamar}/{idBooking}/{idKos}', [App\Http\Controllers\BookingController::class, 'terimaBooking'])->name('terima.booking');
    Route::get('tolak-booking/{idKamar}/{idBooking}/', [App\Http\Controllers\BookingController::class, 'tolakBooking'])->name('tolak.booking');
    Route::get('booking-kos-masuk', [App\Http\Controllers\BookingController::class, 'bookinganKosMasuk'])->name('booking-kos-masuk');
    Route::get('riwayat-kos-saya', [App\Http\Controllers\BookingController::class, 'bookinganSaya'])->name('riwayat-kos-saya');
    Route::get('semua-kos', [App\Http\Controllers\KosController::class, 'tableKos'])->name('semua-kos');
    Route::get('aktifkan-kos/{id}', [App\Http\Controllers\KosController::class, 'aktifkan'])->name('kos.aktifkan');
    Route::get('nonaktifkan-kos/{id}', [App\Http\Controllers\KosController::class, 'nonaktifkan'])->name('kos.nonaktifkan');
    Route::get('kos-tersimpan/{id}/delete', [App\Http\Controllers\KosTersimpanController::class, 'delete'])->name('delete.kos-tersimpan');
    Route::get('delete-gallery/{id}', [App\Http\Controllers\GambarKosController::class, 'deleteGalery'])->name('delete-gallery');
    Route::get('delete-kos/{id}', [App\Http\Controllers\KosController::class, 'deleteKos'])->name('delete-kos');
    Route::get('create-gallery/{id}', [App\Http\Controllers\KosController::class, 'createGallery'])->name('createGallery');
    Route::get('create-gallery-kamar/{id}', [App\Http\Controllers\GambarKamarController::class, 'createGalleryKamar'])->name('gallery.kamar');
    Route::get('delete-gallery-kamar/{id}', [App\Http\Controllers\GambarKamarController::class, 'deleteGalleryKamar'])->name('gallery-kamar.delete');
    Route::get('/ajax/fasilitas-kos/search', [App\Http\Controllers\FasilitasController::class, 'ajaxSearch']);

    Route::get('cetak-pdf/{id}', [App\Http\Controllers\BookingController::class, 'cetakPdf'])->name('cetakPdf');
    Route::get('cetak-semua-booking', [App\Http\Controllers\BookingController::class, 'setakBookingSukses'])->name('cetak-semua-booking');
});


// api untuk tampilkan seluruh data kost
Route::get('/api/data-kost/all', [App\Http\Controllers\Api\KosController::class, 'dataKostAll']);
Route::get('/api/data-kost/detail/{nama_kost}', [App\Http\Controllers\Api\KosController::class, 'dataDetailKost']);
Route::get('/api/data-kost/detail_id/{id_kost}', [App\Http\Controllers\Api\KosController::class, 'dataDetailKostId']);
Route::get('/api/data-kost/getKos/{latitude}/{longitude}', [App\Http\Controllers\Api\KosController::class, 'getKos']);

resources/views/pages/browseMaps.blade.php
@extends('layouts.landingPage')

@section('title')
Maps Kos
@stop


@section('content')
<style>
  .text-brand {
    color: #fff !important;
  }

  .nav-link {
    color: #fff !important;
  }

  /* percobaan mas alan*/
</style>
<section class="intro-single">
  <div class="container">
    <div class="row">
      <div class="col-md-12 col-lg-8">
        <div class="title-single-box">
          <h6>Pemetaan Lokasi Kos-kosan</h6>
        </div>
      </div>
      <div class="col-md-12 col-lg-4">
        <nav aria-label="breadcrumb" class="breadcrumb-box d-flex justify-content-lg-end">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="{{route('home')}}">Home</a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">
              Peta
            </li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</section>
<!--  -->
<section class="property-grid grid">
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <div style="height: 500px" id="mapContainer"></div>
      </div>
    </div>
  </div>
</section>
@stop

@push('scripts')
<script>
  window.action = "browse"
</script>
@endpush

resources/views/pages/checkout.blade.php
@extends('layouts.landingPage')

@section('title')
    Booking
@stop

@section('content')
  <!--/ Intro Single star /-->
  <section class="intro-single">
    <div class="container">
      <div class="row">
        <div class="col-md-12 col-lg-8">
          <div class="title-single-box">
            <h5 class="title-single">Booking kos - {{$kamar->kos->nama_kos}}</h5> <br>
            <span class="badge badge-sm badge-success">{{number_format($kamar->biaya_perbulan)}}  /  Bulan</span>
          </div>
        </div>
        <div class="col-md-12 col-lg-4">
          <nav aria-label="breadcrumb" class="breadcrumb-box d-flex justify-content-lg-end">
            <ol class="breadcrumb">
              <li class="breadcrumb-item">
                <a href="{{url('/')}}">Home</a>
              </li>
              <li class="breadcrumb-item active" aria-current="page">
                {{$kamar->kos->nama_kos}}
              </li>
              <li class="breadcrumb-item active" aria-current="page">
                ID Kamar - {{$kamar->id}}
              </li>
            </ol>
          </nav>
        </div>
      </div>
    </div>
  </section>
  <!--/ Intro Single End /-->

  <!--/ Contact Star /-->
  <section class="contact">
    <div class="container">
      <div class="row" style="margin-top : -100px;">
        <div class="col-sm-12 section-t8">
          <div class="row">
            <div class="col-md-6 col-lg-6 col-sm-12 section-md-t3">
                <img src="{{asset('backend/image/galeri_kamar/'.$kamar->galleryKamar->first()->gambar)}}" width="350px">
            </div>
            <div class="col-md-6 col-lg-6 col-sm-12">
                <form action="{{route('booking.store')}}" method="post" enctype="multipart/form-data">
                    <input name="kos_id" value="{{$kamar->kos->id}}" type="hidden">
                    <input name="kamar_id" value="{{$kamar->id}}" type="hidden">
                    <input type="hidden" value="{{$kamar->biaya_perbulan}}" name="biaya">
                            @csrf
                        <div class="form-group">
                            <label for="mulai_sewa">Mulai Sewa</label>
                            <input required type="date" class="form-control" id="mulai_sewa" name="mulai_sewa">
                        </div>
                        <div class="form-group">
                            <label for="habis_sewa">Hingga</label>
                            <input required type="date" class="form-control" id="habis_sewa" name="habis_sewa">
                        </div>
                        <div class="form-group">
                            <label for="bukti_bayar">Bukti Pembayaran DP</label>
                            <input required type="file" class="form-control" id="bukti_bayar" name="bukti_bayar">
                        </div>
                        <div class="form-group">
                            <label for="bank_id">Kirim Ke Rekening</label>
                            <select required name="bank_id" id="bank_id" class="form-control">
                                <option value="0" disabled selected>Pilih Rekening</option>
                                @foreach($banks  as $bank)
                                <option value="{{$bank->id}}">{{$bank->nama_bank}} - {{$bank->no_rek}} an {{$bank->nama_nasabah}}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <div class="custom-control custom-checkbox">
                                <input required type="checkbox" name="agree" class="custom-control-input" id="agree">
                                <label class="custom-control-label text-muted" for="agree" style="font-size: 12px;">
                                    Ketentuan Untuk Booking Pada Kos {{$kamar->kos->nama_kos}} adalah {{$kamar->biaya_perbulan}} <br>
                                    Saya Mengerti Dan Saya Setuju Dengan Aturan Booking Kos {{$kamar->kos->nama_kos}}
                                </label>
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn btns-m btn-block btn-sm btn-warning text-white mt-3 shadow" style="margin-bottom: 120px;">
                        Booking
                    </button>
                </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!--/ Contact End /-->
@stop

resources/views/pages/detail-blog.blade.php
@extends('layouts.landingPage')

@section('title')
    Detail {{$blog->slug}}
@stop

@section('content')
  <!--/ Intro Single star /-->
  <section class="intro-single">
    <div class="container">
      <div class="row">
        <div class="col-md-12 col-lg-8">
          <div class="title-single-box">
            <h4 class="title-single">{{$blog->title}}</h4>
          </div>
        </div>
        <div class="col-md-12 col-lg-4">
          <nav aria-label="breadcrumb" class="breadcrumb-box d-flex justify-content-lg-end">
            <ol class="breadcrumb">
              <li class="breadcrumb-item">
                <a href="{{url('/')}}">Home</a>
              </li>
              <li class="breadcrumb-item active" aria-current="page">
                {{$blog->title}}
              </li>
            </ol>
          </nav>
        </div>
      </div>
    </div>
  </section>
  <!--/ Intro Single End /-->

  <!--/ News Single Star /-->
  <section class="news-single nav-arrow-b">
    <div class="container">
      <div class="row">
        <div class="col-sm-12">
          <div class="text-center news-img-box">
            <img src="{{Storage::url($blog->gambar)}}" style="width: 500px;" alt="" class="img-fluid ">
          </div>
        </div>
        <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
          <div class="post-information">
            <ul class="text-center list-inline color-a">
              <li class="mr-2 list-inline-item">
                <strong>Penulis: </strong>
                <span class="color-text-a">{{$blog->author}}</span>
              </li>
              <li class="mr-2 list-inline-item">
                <strong>Kategori: </strong>
                <span class="color-text-a">{{$blog->kategori}}</span>
              </li>
              <li class="list-inline-item">
                <strong>Tanggal: </strong>
                <span class="color-text-a">{{date('d M. Y',strtotime($blog->created_at))}}</span>
              </li>
            </ul>
          </div>
          <div class="post-content color-text-a">
            <p class="post-intro">
            <p>
              {!!$blog->isi!!}
            </p>
            @if($blog->quote)
            <blockquote class="blockquote">
              <p class="mb-4">{{$blog->quote}}.</p>
              <footer class="blockquote-footer">
                <strong>{{$blog->quote_author}}</strong>
                <cite title="Source Title"></cite>
              </footer>
            </blockquote>
            @endif
          </div>
        </div>
      </div>
    </div>
  </section>
  <!--/ News Single End /-->
@endsection

resources/views/pages/lihat-semua-blog.blade.php
@extends('layouts.landingPage')

@section('title')
    Cari Kosan
@endsection

@section('content')
  <!--/ Intro Single star /-->
  <section class="intro-single">
    <div class="container">
      <div class="row">
        <div class="col-md-12 col-lg-8">
          <div class="title-single-box">
            <h6> Kosan Terdekat</h6>
          </div>
        </div>
        <div class="col-md-12 col-lg-4">
          <nav aria-label="breadcrumb" class="breadcrumb-box d-flex justify-content-lg-end">
            <ol class="breadcrumb">
              <li class="breadcrumb-item">
                <a href="{{url('/')}}">Home</a>
              </li>
              <li class="breadcrumb-item active" aria-current="page">
                Kosan Terdekat
              </li>
            </ol>
          </nav>
        </div>
      </div>
    </div>
  </section>
  <!--/ Intro Single End /-->

  <!--/ News Grid Star /-->
  <section class="grid mb-5 news-grid">
    <div class="container">
      <div class="row">
        <!-- @foreach($blogs as $blog) -->
        <div class="col-md-4">
          <div class="card-box-b card-shadow news-box">
          <div id="map" class="contact-map">
              <div style="height: 500px" id="mapContainer"></div>
            <div id="summary"></div>
          </div>
          </div>
        </div>
        <!-- @endforeach -->
      </div>
    </div>
  </section>
  <!--/ News Grid End /-->
@endsection

resources/views/pages/semua-kos.blade.php
@extends('layouts.landingPage')

@section('title')
Semua Kos
@stop

@section('content')
<style>
    .text-brand {
        color: #fff !important;
    }

    .nav-link {
        color: #fff !important;
    }
</style>
<section class="intro-single">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-lg-8">
                <div class="title-single-box">
                    <h6>Semua Kos-kosan Usakti Kos</h6>
                </div>
            </div>
            <div class="col-md-12 col-lg-4">
                <nav aria-label="breadcrumb" class="breadcrumb-box d-flex justify-content-lg-end">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">
                            <a href="{{url('/')}}">Home</a>
                        </li>
                        <li class="breadcrumb-item" aria-current="page">
                            <a href="{{route('object-kos.index')}}">Semua Kos</a>
                        </li>
                    </ol>
                </nav>
            </div>
        </div>
        <!-- <div id="mapContainer" style="width: 640px; height: 480px"></div> -->
    </div>
</section>
<!--  -->
<section class="grid property-grid">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="grid-option">
                    <!-- <form action="{{route('object-kos.index')}}">
                        <input type="text" name="keyword" placeholder="Cari alamat kos..">
                    </form> -->
                </div>
            </div>
            @foreach($kosan as $kos)
            @php $jmlKamar = $kos->kamar->where('status','tersedia')->count(); @endphp
            @if($jmlKamar > 0)
            <div class="col-md-4">
                <div class="card-box-a card-shadow">
                    <div class="img-box-a">
                        <img src="{{ asset('backend/image/gambar_kos/'.$kos->gallery->first()->gambar )}}" style="height:400px;" class="w-100 img-a img-fluid">
                    </div>
                    <div class="card-overlay">
                        <div class="card-overlay-a-content">
                            <div class="card-header-a">
                                <h2 class="card-title-a">
                                    <a href="{{ env('APP_URL') }}/object-kos/{{ $kos -> id }}/0" target="_blank">{{$kos->nama_kos}} </a>
                                    <br />
                                    <span class="text-white" style="font-size:12px; ">Lokasi: {{$kos->alamat}}</span>
                                </h2>
                            </div>
                            <div class="card-body-a">
                                <!-- <div class="price-box d-flex"> -->
                                <!-- <a class="price-a" href="{{route('kos.detail',$kos->slug)}}">
                                    Detail
                                </a> -->
                                <!-- <a href="javascript:void(0)" onclick="openKostDetail('{{ $kos -> latitude }}', '{{ $kos -> longitude }}', '{{ $kos -> id }}')" class="price-a">Detail</a> -->
                                <!-- <a href="javascript:void(0)" class="price-a"></a> -->
                                <!-- </div> -->
                            </div>
                            <div class="card-footer-a">
                                <ul class="card-info d-flex justify-content-around">
                                    <li>
                                        <a href="{{ env('APP_URL') }}/object-kos/{{ $kos -> id }}/0" target="_blank">
                                            <h4 class="card-info-title">Lihat Detail</h4>
                                        </a>
                                        <!-- <h4 class="card-info-title">Kamar Kosong</h4>
                                        @php $k = $kos->kamar->where('status','=','tersedia')->count(); @endphp
                                        <span> {{$k}}</span> -->
                                    </li>
                                    <!-- @foreach($kos->fasilitas as $fasilitas)
                                    <li>
                                        <h4 class="card-info-title">
                                            {{$fasilitas->nama_fasilitas == 'penjaga' ? 'Penjaga' : ''}}
                                        </h4>
                                        <span>{{$fasilitas->nama_fasilitas == 'penjaga' ? 'Tersedia' : ''}}</span>
                                    </li>
                                    <li>
                                        <h4 class="card-info-title">
                                            {{$fasilitas->nama_fasilitas == 'garasi' ? 'garasi' : ''}}
                                        </h4>
                                        <span>{{$fasilitas->nama_fasilitas == 'garasi' ? 'Tersedia' : ''}} </span>
                                    </li>
                                    @endforeach -->
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            @endif
            @endforeach
        </div>
        <div class="mt-3 row">
            <div class="text-center col-12">
                {{$kosan->links()}}
            </div>
        </div>
    </div>
</section>
@stop
@push('scripts')
<script>
    var latDef = 0;
    var lngDef = 0;
    var platform;
    var defaultLayers;
    var map;

    function getLocation() {
        if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(showPosition);
        } else {
            // x.innerHTML = "Geolocation is not supported by this browser.";
        }
    }

    function showPosition(position) {
        latDef = position.coords.latitude;
        lngDef = position.coords.longitude;
    }

    getLocation();

    function openKostDetail(latTujuan, lngTujuan, idKost) {
        let linkOpen = server + "object-kos/" + idKost + "?from=" + latDef + "," + lngDef + "&to=" + latTujuan + "," + lngTujuan;
        window.open(linkOpen);
        // console.log(linkOpen);
    }
</script>

@endpush

resources/views/pages/success.blade.php
<!--BISMILLAHI-->

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport"content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="" />
    <meta name="author" content="" />

    <title>Success Order</title>
    <style>
    	.page-success .section-success {
		  font-size: 28px;
		  font-weight: 200;
		  text-align: center;
		  color: #0c0d36;
		  margin-top: 0;
		}
    </style>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
  </head>

  <body>

    <div class="page-content page-success">
        <div class="section-success" data-aos="zoom-in">
            <div class="container">
                <div class="row align-items-center row-login justify-content-center">
                    <div class="col-lg-6 text-center mt-5">
                        <img src="/frontend/img/success.png" class="mb-4" style="width: 300px;"> <br>
                        <p style="font-size: 24px;">Booking Kos Berhasil. Booking Anda Akan Segera Dicek Pemilik Kos.</p>
                        <div class="text-muted" style="font-size: 20px;">
                          <a href="{{route('home')}}" class="btn mb-2 px-5 btn-sm btn-success">Dshboard</a> <br>
                        	<a href="{{url('/')}}" class="btn px-5 btn-sm btn-secondary">Home</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>

  </body>
</html>